### ISSUE TITLE
Peer-to-peer code reviews

### ISSUE THREAD

**Issue by Abdelaziz-Mahdi** [Mukaba/Portfolio_Microverse#5]
1- Contact me section :
- Button  Color should match Figma design.
2- About myself section :
- Missing arrow beside language
3- works section:
- replace images for desktop version.
* Suggestions
- All project export background image from figma to replace the divs in html.
- Add menu nested inside Nav rather than background image.

Every thing else in the project is fine and nice.
Thanks Jean.

**Comment by emarkees** [comment]
Great work done🤗 so far!!

But i think the background image could  be close into one div, instead of have different div for each shape.

also for you left item, you can add a list [ul] tags 🏷️ 


Happy coding

**Comment by Mukaba** [comment]
Thanks guys for all of your suggestions, I will make sure to update my code.

_Great regards_
